version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - uv pip install -e ".[docs]"

python:
  install:
    - method: pip
      path: .

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
